[package]
name = "hello-rust-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.8.0"
aws-sdk-ec2 = "0.8.0"
tokio = { version = "1.37.0", features = ["full"] }
