[package]
name = "hello-rust-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.0.0"
aws-sdk-ec2 = "1.0.0"
tokio = { version = "1", features = ["full"] }
